//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public int bill_id { get; set; }
        public int customer_id { get; set; }
        public int bill_total { get; set; }
        public System.DateTime bill_date { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
